"""empty message

Revision ID: 210426be5f19
Revises: 
Create Date: 2023-04-08 22:54:32.259210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210426be5f19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
