"""empty message

Revision ID: 50fe7b483c15
Revises: 224821a1461e
Create Date: 2023-04-22 23:22:22.140439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50fe7b483c15'
down_revision = '224821a1461e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
