"""empty message

Revision ID: e5883c87ccc6
Revises: 1228d61e04e4
Create Date: 2023-04-25 21:43:11.528326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5883c87ccc6'
down_revision = '1228d61e04e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resumes')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('templates')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'templates',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('preview', sa.VARCHAR(), nullable=True),
        sa.Column('template_name', sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'users',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('avatar', sa.VARCHAR(), nullable=True),
        sa.Column('username', sa.VARCHAR(), nullable=True),
        sa.Column('bio', sa.VARCHAR(), nullable=True),
        sa.Column('email', sa.VARCHAR(), nullable=True),
        sa.Column('hashed_password', sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table(
        'resumes',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('user_id', sa.INTEGER(), nullable=True),
        sa.Column('template_id', sa.INTEGER(), nullable=True),
        sa.Column('name', sa.VARCHAR(), nullable=True),
        sa.Column('image', sa.BLOB(), nullable=True),
        sa.Column('position', sa.VARCHAR(), nullable=True),
        sa.Column('email', sa.VARCHAR(), nullable=True),
        sa.Column('place_of_residence', sa.VARCHAR(), nullable=True),
        sa.Column('skills', sa.VARCHAR(), nullable=True),
        sa.Column('expierence', sa.VARCHAR(), nullable=True),
        sa.Column('education', sa.VARCHAR(), nullable=True),
        sa.Column('achievments', sa.VARCHAR(), nullable=True),
        sa.ForeignKeyConstraint(
            ['template_id'],
            ['templates.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###
